<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Http;

/*
|--------------------------------------------------------------------------
| Public Twilio SMS Webhook
|--------------------------------------------------------------------------
*/
Route::post('/sms', function (Request $request) {

    $message = strtolower($request->input('Body'));
    $from = $request->input('From');

    $calloffPhrases = [
        'call off',
        'call of',
        'called off',
        'calling off',
        'sick',
        'not coming',
        'not coming in',
        'cant make it',
        "can't make it",
        'cannot make it',
        'wont make it',
        "won't make it",
        'cant come in',
        "can't come in",
        'cannot come in',
        'not going in',
        'miss work',
        'missing work',
        'out today',
        'car broke down',
        'family emergency',
        'emergency',
        'no ride',
        'running a fever',
        'throwing up',
        'injured',
        'hospital',
        'no puedo ir',
        'no puedo llegar',
        'no voy a ir',
        'no ire',
        'no iré',
        'no puedo trabajar',
        'me siento enfermo',
        'me siento enferma',
        'estoy enfermo',
        'estoy enferma',
        'estoy malo',
        'estoy mala',
        'me enferme',
        'me enfermé',
        'tengo fiebre',
        'vomitando',
        'tengo emergencia',
        'emergencia familiar',
        'se me descompuso el carro',
        'no tengo transporte',
        'no tengo ride',
        'no puedo presentarme',
        'no puedo asistir',
    ];

    $status = 'OTHER';
    $reason = 'Other';	

foreach ($calloffPhrases as $phrase) {

    if (str_contains($message, $phrase)) {

        $status = 'CALLOFF';

        if (
            str_contains($message, 'sick') ||
            str_contains($message, 'fever') ||
            str_contains($message, 'hospital') ||
            str_contains($message, 'enfermo') ||
            str_contains($message, 'enferma')
        ) {

            $reason = 'Sick';

        } elseif (
            str_contains($message, 'car') ||
            str_contains($message, 'ride') ||
            str_contains($message, 'transport') ||
            str_contains($message, 'traffic')
        ) {

            $reason = 'Transportation';

        } elseif (
            str_contains($message, 'family') ||
            str_contains($message, 'emergency')
        ) {

            $reason = 'Family Emergency';

        } else {

            $reason = 'General Call-Off';

        }

        break;
    }
}

$recentDuplicate = DB::table('messages')
    ->where('from', $from)
    ->whereIn('status', ['CALLOFF', 'DUPLICATE'])
    ->where('body', $message)
    ->where('created_at', '>=', now()->subMinutes(10))
    ->exists();

$finalStatus = $status;

if ($status === 'CALLOFF' && $recentDuplicate) {
    $finalStatus = 'DUPLICATE';
}

    $messageId = DB::table('messages')->insertGetId([
        'from' => $from,
        'body' => $message,
        'status' => $finalStatus,
	'reason' => $reason,
        'created_at' => now(),
        'updated_at' => now(),
    ]);

    $employee = DB::table('employees')
        ->where('phone', $from)
        ->first();

    $name = $employee ? $employee->name : 'Unknown Employee';

    $clientName = $employee
        ? $employee->client_name
        : 'N/A';

    $client = DB::table('clients')
        ->where('name', strtolower($clientName))
        ->first();

    if ($finalStatus === 'CALLOFF') {

        $emailBody = "
CALL OFF ALERT

Employee: $name

Client: $clientName

Phone: $from

Reason: $reason

Time: " . now()->format('m/d/Y g:i A') . "

Message:
$message

This alert was automatically generated by CallOffApp.
";

        if ($client && $client->notify_email && $client->notification_email) {
try {

    Mail::raw($emailBody, function ($mail) use ($client, $name) {

        $mail->to($client->notification_email)
            ->subject("Call Off Alert - $name");

    });

    DB::table('messages')
        ->where('id', $messageId)
        ->update([
            'notification_sent' => true,
            'notification_sent_at' => now(),
        ]);

} catch (\Exception $e) {

    DB::table('messages')
        ->where('id', $messageId)
        ->update([
            'notification_error' => $e->getMessage(),
        ]);

}
        }
    }

    return response(
        '<Response><Message>Your call-off has been received.</Message></Response>',
        200
    )->header('Content-Type', 'text/xml');
});

/*
|--------------------------------------------------------------------------
| Admin Login Routes
|--------------------------------------------------------------------------
*/
Route::get('/admin-login', function () {
    return view('admin-login');
});

Route::post('/admin-login', function (Request $request) {

    if (
        $request->email === env('ADMIN_EMAIL') &&
        $request->password === env('ADMIN_PASSWORD')
    ) {
        session(['admin_logged_in' => true]);

        return redirect('/messages');
    }

    return 'Admin login failed';
});

Route::get('/admin-logout', function () {
    session()->forget('admin_logged_in');

    return redirect('/admin-login');
});

/*
|--------------------------------------------------------------------------
| Admin Dashboard / Messages
|--------------------------------------------------------------------------
*/
Route::get('/messages/{id}/resolve', function ($id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('messages')
        ->where('id', $id)
        ->update([
            'resolved' => true,
            'resolved_at' => now(),
            'updated_at' => now(),
        ]);

    return redirect('/messages');
});

Route::get('/messages/{id}/acknowledge', function ($id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('messages')
        ->where('id', $id)
        ->update([
            'acknowledged' => true,
            'acknowledged_at' => now(),
            'updated_at' => now(),
        ]);

    return redirect('/messages');
});

Route::get('/messages', function (Request $request) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    $query = DB::table('messages')
        ->leftJoin('employees', 'messages.from', '=', 'employees.phone')
        ->select(
            'messages.*',
            'employees.name as employee_name',
            'employees.client_name as client_name'
        );

    if ($request->input('calloff') == 1) {
        $query->where('messages.status', 'CALLOFF');
    }

    if ($request->input('search')) {

        $search = $request->input('search');

        $query->where(function ($q) use ($search) {
            $q->where('messages.from', 'like', "%$search%")
              ->orWhere('messages.body', 'like', "%$search%")
              ->orWhere('employees.name', 'like', "%$search%")
              ->orWhere('employees.client_name', 'like', "%$search%");
        });
    }

    $messages = $query
        ->orderByDesc('messages.created_at')
        ->get();

    $todayCalloffs = DB::table('messages')
        ->where('status', 'CALLOFF')
        ->whereDate('created_at', today())
        ->count();

    $clientSummary = DB::table('messages')
        ->leftJoin('employees', 'messages.from', '=', 'employees.phone')
        ->select('employees.client_name', DB::raw('count(*) as total'))
        ->where('messages.status', 'CALLOFF')
        ->whereDate('messages.created_at', today())
        ->groupBy('employees.client_name')
        ->get();

    return view('messages', [
        'messages' => $messages,
        'todayCalloffs' => $todayCalloffs,
        'clientSummary' => $clientSummary
    ]);
});
Route::get('/calendar', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    $calloffs = DB::table('messages')
        ->leftJoin('employees', 'messages.from', '=', 'employees.phone')
        ->select(
            'messages.*',
            'employees.name as employee_name',
            'employees.client_name as client_name'
        )
        ->where('messages.status', 'CALLOFF')
        ->latest()
        ->get();

    return view('calendar', compact('calloffs'));

});

/*
|--------------------------------------------------------------------------
| Employees Admin
|--------------------------------------------------------------------------
*/
Route::get('/employees', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    $employees = DB::table('employees')
        ->orderByDesc('created_at')
        ->get();

    return view('employees', [
        'employees' => $employees
    ]);
});

Route::get('/employees/create', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    return view('employees-create');
});

Route::post('/employees', function (Request $request) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('employees')->insert([
        'name' => $request->name,
        'phone' => $request->phone,
        'client_name' => strtolower($request->client_name),
        'client_email' => $request->client_email,
        'active' => true,
        'created_at' => now(),
        'updated_at' => now(),
    ]);

    return redirect('/employees');
});

Route::get('/employees/{id}/edit', function ($id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    $employee = DB::table('employees')
        ->where('id', $id)
        ->first();

    return view('employees-edit', [
        'employee' => $employee
    ]);
});

Route::post('/employees/{id}/update', function (Request $request, $id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('employees')
        ->where('id', $id)
        ->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'client_name' => strtolower($request->client_name),
            'client_email' => $request->client_email,
            'updated_at' => now(),
        ]);

    return redirect('/employees');
});

Route::get('/employees/delete/{id}', function ($id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('employees')
        ->where('id', $id)
        ->delete();

    return redirect('/employees');
});

/*
|--------------------------------------------------------------------------
| Daily Summary Admin Page
|--------------------------------------------------------------------------
*/
Route::get('/send-daily-summary', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    $today = now()->toDateString();

    $calloffs = DB::table('messages')
        ->leftJoin('employees', 'messages.from', '=', 'employees.phone')
        ->select(
            'messages.*',
            'employees.name as employee_name',
            'employees.client_name'
        )
        ->where('messages.status', 'CALLOFF')
        ->whereDate('messages.created_at', $today)
        ->orderBy('messages.created_at', 'desc')
        ->get();

    return view('daily-summary', [
        'calloffs' => $calloffs
    ]);
});
Route::get('/testing-checklist', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    return view('testing-checklist');

});

/*
|--------------------------------------------------------------------------
| Client Portal Login / Dashboard
|--------------------------------------------------------------------------
*/
Route::get('/login', function () {
    return view('login');
});

Route::post('/login', function (Request $request) {

    $client = DB::table('clients')
        ->where('email', $request->email)
        ->first();

    if ($client && $request->password === $client->password) {

        session([
            'client' => $client->name
        ]);

        return redirect('/client/' . $client->name);
    }

    return 'Login failed';
});

Route::get('/logout', function () {

    session()->flush();

    return redirect('/login');
});

Route::get('/client/{client}', function ($client) {

    if (session('client') !== $client) {
        return redirect('/login');
    }

    $messages = DB::table('messages')
        ->leftJoin('employees', 'messages.from', '=', 'employees.phone')
        ->select(
            'messages.*',
            'employees.name as employee_name',
            'employees.client_name as client_name'
        )
        ->where('employees.client_name', $client)
        ->orderByDesc('messages.created_at')
        ->get();

    return view('client', [
        'messages' => $messages,
        'client' => $client
    ]);
});

/*
|--------------------------------------------------------------------------
| Clients Admin
|--------------------------------------------------------------------------
*/
Route::get('/clients', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    $clients = DB::table('clients')
        ->orderByDesc('created_at')
        ->get();

    return view('clients', [
        'clients' => $clients
    ]);
});

Route::get('/clients/create', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    return view('clients-create');
});

Route::get('/clients/{id}/edit', function ($id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    $client = DB::table('clients')
        ->where('id', $id)
        ->first();

    return view('clients-edit', [
        'client' => $client
    ]);
});

Route::post('/clients/{id}/update', function (Request $request, $id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('clients')
        ->where('id', $id)
        ->update([
            'name' => strtolower($request->name),
            'email' => $request->email,
            'password' => $request->password,
            'notification_email' => $request->notification_email,
            'notification_phone' => $request->notification_phone,
            'notify_email' => $request->has('notify_email'),
            'notify_sms' => $request->has('notify_sms'),
            'updated_at' => now(),
        ]);

    return redirect('/clients');
});

Route::post('/clients', function (Request $request) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('clients')->insert([
        'name' => strtolower($request->name),
        'email' => $request->email,
        'password' => $request->password,
        'notification_email' => $request->notification_email,
        'notification_phone' => $request->notification_phone,
        'notify_email' => $request->has('notify_email'),
        'notify_sms' => $request->has('notify_sms'),
        'created_at' => now(),
        'updated_at' => now(),
    ]);

    return redirect('/clients');
});

Route::get('/clients/delete/{id}', function ($id) {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    DB::table('clients')
        ->where('id', $id)
        ->delete();

    return redirect('/clients');
});

/*
|--------------------------------------------------------------------------
| Public Twilio Voice Webhooks
|--------------------------------------------------------------------------
*/
Route::match(['get', 'post'], '/voice', function () {

    return response('<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Say voice="alice">Please leave your call-off message after the beep. When finished, hang up.</Say>
    <Say voice="alice" language="es-MX">Por favor deje su mensaje despues del tono. Cuando termine, cuelgue.</Say>
    <Record
        maxLength="60"
        playBeep="true"
        recordingStatusCallback="https://calloff-app-1.onrender.com/voice-recording"
        recordingStatusCallbackMethod="POST"
    />
    <Say voice="alice">Thank you. Your call-off has been received. Goodbye.</Say>
    <Hangup/>
</Response>', 200)->header('Content-Type', 'text/xml');

});

Route::match(['get', 'post'], '/voice-recording', function (Request $request) {

    DB::table('messages')->insert([
        'from' => $request->From,
        'body' => 'Voice call received',
        'status' => 'CALLOFF',
        'reason' => 'Voice Call-Off',
        'recording_url' => $request->RecordingUrl,
        'transcription_status' => 'pending',
        'created_at' => now(),
        'updated_at' => now(),
    ]);

    return response('OK', 200);

});
/*
|--------------------------------------------------------------------------
| Public API Endpoints for Future Base44 Frontend
|--------------------------------------------------------------------------
*/

Route::get('/api/calloffs', function () {

    return DB::table('messages')
        ->leftJoin('employees', 'messages.from', '=', 'employees.phone')
        ->select(
            'messages.id',
            'messages.from',
            'messages.body',
            'messages.status',
	    'messages.reason',
            'messages.recording_url',
            'messages.transcription',
            'messages.transcription_status',
            'messages.acknowledged',
            'messages.acknowledged_at',
            'messages.resolved',
            'messages.resolved_at',
            'messages.notification_sent',
            'messages.notification_sent_at',
            'messages.notification_error',
            'messages.created_at',
            'employees.name as employee_name',
            'employees.client_name as client_name'
        )
        ->orderByDesc('messages.created_at')
        ->get();

});

Route::get('/api/employees', function () {

    return DB::table('employees')
        ->orderBy('name')
        ->get();

});

Route::get('/api/clients', function () {

    return DB::table('clients')
        ->orderBy('name')
        ->get();

});

Route::get('/api/dashboard-stats', function () {

    return [
        'today_calloffs' => DB::table('messages')
            ->where('status', 'CALLOFF')
            ->whereDate('created_at', today())
            ->count(),

        'week_calloffs' => DB::table('messages')
            ->where('status', 'CALLOFF')
            ->whereBetween('created_at', [
                now()->startOfWeek(),
                now()->endOfWeek()
            ])
            ->count(),

        'total_employees' => DB::table('employees')->count(),

        'total_clients' => DB::table('clients')->count(),

        'open_calloffs' => DB::table('messages')
            ->where('status', 'CALLOFF')
            ->where(function ($q) {
                $q->where('resolved', false)
                  ->orWhereNull('resolved');
            })
            ->count(),
    ];

});

Route::get('/api/calendar', function () {

    return DB::table('messages')
        ->leftJoin('employees', 'messages.from', '=', 'employees.phone')
        ->select(
            'messages.id',
            'messages.body',
            'messages.status',
            'messages.created_at',
            'employees.name as employee_name',
            'employees.client_name as client_name'
        )
        ->whereIn('messages.status', ['CALLOFF', 'DUPLICATE'])
        ->orderByDesc('messages.created_at')
        ->get();

});
/*
|--------------------------------------------------------------------------
| Admin-Only Migration Runner
|--------------------------------------------------------------------------
*/
Route::get('/run-migrations', function () {

    if (!session('admin_logged_in')) {
        return redirect('/admin-login');
    }

    Artisan::call('migrate', ['--force' => true]);

    return nl2br(Artisan::output());
});
